name: watermark
description: 一键去水印，谁用谁知道.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  dio: ^2.1.8
  connectivity: ^0.4.3+2
  flutter_webview_plugin: ^0.3.0+2
  objectdb: ^1.0.5
  path_provider: ^1.1.0
  cached_network_image: ^1.0.0
  oktoast: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: IconFont
      fonts:
        - asset: static/font/iconfont.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: static/font/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: static/font/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: static/font/WorkSans-Medium.ttf

    - family: WorkSansLight
      fonts:
        - asset: static/font/WorkSans-Light.ttf
